---
abstract: 'Struct oriented CSS manipulation.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.05
  Test::More: 0
  Test::NoWarnings: 0
  Test::Output: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CSS-Struct
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Utils: 0.03
  Error::Pure: 0.11
  List::MoreUtils: 0
  Readonly: 0
  Scalar::Util: 0
resources:
  bugtracker: https://github.com/michal-josef-spacek/CSS-Struct/issues
  homepage: https://github.com/michal-josef-spacek/CSS-Struct
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/CSS-Struct
version: '0.05'
